### ISSUE TITLE
'Min Upgrade Format Score' must be greater than or equal to '1'

### ISSUE THREAD

**Issue by giovannibaratta** [devopsarr/ansible-collection-radarr#26]
After upgrading Radarr from version 5.8.3 to 5.11.0, quality profiles (devopsarr.radarr.radarr_quality_profile) cannot to be updated anymore.

The error message is `'Min Upgrade Format Score' must be greater than or equal to '1'`. 

It seems that Radarr introduced a new attribute that is not optional https://github.com/Radarr/Radarr/pull/10439 and there is no way to defined the value of this attribute in the version 1.1.0 of the module.

The same error is happening in the integration tests of this PR https://github.com/devopsarr/ansible-collection-radarr/actions/runs/11031299418/job/30637739556?pr=25 .

**Comment by Fuochi** [comment]
Hi @giovannibaratta,
Thanks for the ticket. I am aware of the issue, the SDK has already been updated, and I need to create a new release (devopsarr/radarr-py#82) then update the ansible collection. I'll try to find time to do that soon, but it'll probably take a couple of weeks.

**Comment by Fuochi** [comment]
Hi @giovannibaratta,
Could you try v1.2.0? (you'll also have to update radarr-py)

**Comment by giovannibaratta** [comment]
Hi @Fuochi ,
I updated the module to v1.2.0 and radarr-py to v1.1.1 and now it works. Thanks for the release.
